CREATE DATABASE VENTASDB;
GO

USE VENTASDB;
GO

CREATE SCHEMA CLIENTES;
GO

CREATE TABLE CLIENTES.REGIONES(
	IDREGION INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100)
);

INSERT INTO CLIENTES.REGIONES(NOMBRE) VALUES('REGION 1');
INSERT INTO CLIENTES.REGIONES(NOMBRE) VALUES('REGION 2');
INSERT INTO CLIENTES.REGIONES(NOMBRE) VALUES('REGION 3');
INSERT INTO CLIENTES.REGIONES(NOMBRE) VALUES('REGION 4');
GO

SELECT * FROM CLIENTES.REGIONES;
GO


GRANT SELECT ON CLIENTES.REGIONES TO UserA;
go

CREATE ROLE [ROL_VENTAS]
GO


GRANT SELECT ON SCHEMA::CLIENTES TO UserA;
GO

GRANT SELECT ON SCHEMA::[CLIENTES] TO [ROL_VENTAS]
GO

DENY SELECT ON SCHEMA::[CLIENTES] TO [ROL_VENTAS]
GO

ALTER ROLE [ROL_VENTAS] ADD MEMBER [panchito]
GO

ALTER ROLE [ROL_VENTAS] ADD MEMBER UserA
GO

